/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import Modelo.Clases.Cancion;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN MARIÑO
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneMusica = new javax.swing.JTabbedPane();
        PanelConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultar = new javax.swing.JTable();
        LabelNombreConsultar = new javax.swing.JLabel();
        TFNombreConsultar = new javax.swing.JTextField();
        LabelArtistaConsultar = new javax.swing.JLabel();
        TFArtistaConsultar = new javax.swing.JTextField();
        LabelGeneroConsultar = new javax.swing.JLabel();
        CBGeneroConsultar = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        LabelIDConsultar = new javax.swing.JLabel();
        TFIDConsultar = new javax.swing.JTextField();
        LabelRespuestaConsultar = new javax.swing.JLabel();
        PanelRegistrar = new javax.swing.JPanel();
        TFNombreRegistrar = new javax.swing.JTextField();
        TFArtistaRegistrar = new javax.swing.JTextField();
        CBGeneroRegistrar = new javax.swing.JComboBox<>();
        LabelTituloRegistrar = new javax.swing.JLabel();
        LabelNombreRegistrar = new javax.swing.JLabel();
        LabelArtistaRegistrar = new javax.swing.JLabel();
        LabelGeneroRegistrar = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        LabelRespuestaRegistrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPaneMusica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Artista", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TConsultarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TConsultar);

        LabelNombreConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNombreConsultar.setText("Nombre:");

        TFNombreConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        LabelArtistaConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelArtistaConsultar.setText("Artista:");

        TFArtistaConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TFArtistaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFArtistaConsultarActionPerformed(evt);
            }
        });

        LabelGeneroConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelGeneroConsultar.setText("Genero:");

        CBGeneroConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CBGeneroConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Ranchera", "Ronda", "Bachata", "Salsa", "Merengue", "Reggaeton", "Popular", "Rock" }));

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        LabelIDConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelIDConsultar.setText("ID:");

        TFIDConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        LabelRespuestaConsultar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout PanelConsultarLayout = new javax.swing.GroupLayout(PanelConsultar);
        PanelConsultar.setLayout(PanelConsultarLayout);
        PanelConsultarLayout.setHorizontalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnConsultar)
                                .addGap(60, 60, 60)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(btnActualizar)
                                .addGap(32, 32, 32))
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelArtistaConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNombreConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelGeneroConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelIDConsultar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(53, 53, 53)
                                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFNombreConsultar)
                                    .addComponent(TFArtistaConsultar)
                                    .addComponent(CBGeneroConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFIDConsultar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(LabelRespuestaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelConsultarLayout.setVerticalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelRespuestaConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIDConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFIDConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNombreConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNombreConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelArtistaConsultar)
                    .addComponent(TFArtistaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGeneroConsultar)
                    .addComponent(CBGeneroConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addGap(7, 7, 7))
        );

        TabbedPaneMusica.addTab("Consultar", PanelConsultar);

        TFNombreRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        TFArtistaRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CBGeneroRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CBGeneroRegistrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Ranchera", "Ronda", "Bachata", "Salsa", "Merengue", "Reggaeton", "Popular", "Rock" }));

        LabelTituloRegistrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTituloRegistrar.setText("Music Store");

        LabelNombreRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNombreRegistrar.setText("Nombre:");

        LabelArtistaRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelArtistaRegistrar.setText("Artista:");

        LabelGeneroRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelGeneroRegistrar.setText("Genero:");

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        LabelRespuestaRegistrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelArtistaRegistrar)
                            .addComponent(LabelNombreRegistrar)
                            .addComponent(LabelGeneroRegistrar))
                        .addGap(62, 62, 62)
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFNombreRegistrar)
                            .addComponent(TFArtistaRegistrar)
                            .addComponent(CBGeneroRegistrar, 0, 238, Short.MAX_VALUE)))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(LabelTituloRegistrar))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnRegistrar)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelRespuestaRegistrar)
                .addGap(266, 266, 266))
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloRegistrar)
                .addGap(60, 60, 60)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreRegistrar)
                            .addComponent(TFNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(LabelArtistaRegistrar))
                    .addComponent(TFArtistaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGeneroRegistrar)
                    .addComponent(CBGeneroRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(LabelRespuestaRegistrar)
                .addGap(26, 26, 26))
        );

        TabbedPaneMusica.addTab("Registrar", PanelRegistrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneMusica)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        this.LabelRespuestaRegistrar.setText("");
        String nombre = this.TFNombreRegistrar.getText();
        String artista = this.TFArtistaRegistrar.getText();
        String genero = this.CBGeneroRegistrar.getSelectedItem().toString();

        if (nombre.length() == 0 || artista.length() == 0) {
            this.LabelRespuestaRegistrar.setText("Ingrese valores válidos");
        } else {
            try {
                Controller.registrarCancion(nombre, artista, genero);
                this.LabelRespuestaRegistrar.setText("Valor registrado con éxito");
                this.TFNombreRegistrar.setText("");
                this.TFArtistaRegistrar.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                this.LabelRespuestaRegistrar.setText("Error");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String idString = this.TFIDConsultar.getText();
        DefaultTableModel modelo = (DefaultTableModel) this.TConsultar.getModel();
        modelo.setRowCount(0);
        if (idString.length() == 0) {
            List<Cancion> listaCanciones = Controller.listarCanciones();
            for (int i = 0; i < listaCanciones.size(); i++) {
                Cancion c1 = listaCanciones.get(i);
                modelo.insertRow(i, new Object[]{c1.getID(), c1.getNombre(), c1.getArtista(), c1.getGenero()});
            }
        } else {
            int id = Integer.valueOf(idString);
            Cancion c2 = Controller.obtenerCancion(id);
            modelo.insertRow(0, new Object[]{c2.getID(), c2.getNombre(), c2.getArtista(), c2.getGenero()});
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void TFArtistaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFArtistaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFArtistaConsultarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String ID = this.TFIDConsultar.getText();
//        String nombre = this.TFNombreConsultar.getText();
//        String artista = this.TFArtistaConsultar.getText();
//        String genero = this.CBGeneroConsultar.getSelectedItem().toString();

        if (ID.length() == 0) {
            this.LabelRespuestaConsultar.setText("Ingrese valores válidos");
        } else {
            Controller.borrarCancion(Integer.valueOf(ID));
            this.LabelRespuestaConsultar.setText("Borrado exitoso");
            this.TFIDConsultar.setText("");
            this.TFNombreConsultar.setText("");
            this.TFArtistaConsultar.setText("");
//            this.CBGeneroConsultar.setSelectedItem("Pop");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String ID = this.TFIDConsultar.getText();
        String nombre = this.TFNombreConsultar.getText();
        String artista = this.TFArtistaConsultar.getText();
        String genero = this.CBGeneroConsultar.getSelectedItem().toString();

        if (ID.length() == 0 || nombre.length() == 0 || artista.length() == 0) {
            this.LabelRespuestaConsultar.setText("Ingrese valores válidos");
        } else {
            Controller.actualizarCancion(Integer.valueOf(ID), nombre, artista, genero);
            this.LabelRespuestaConsultar.setText("Actualizacion exitosa");
            this.TFIDConsultar.setText("");
            this.TFNombreConsultar.setText("");
            this.TFArtistaConsultar.setText("");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void TConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConsultarMouseClicked
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        DefaultTableModel modelo = (DefaultTableModel) this.TConsultar.getModel();

        String ID = String.valueOf(modelo.getValueAt(row, 0));
        String nombre = String.valueOf(modelo.getValueAt(row, 1));
        String artista = String.valueOf(modelo.getValueAt(row, 2));
        String genero = String.valueOf(modelo.getValueAt(row, 3));

        this.TFIDConsultar.setText(ID);
        this.TFNombreConsultar.setText(nombre);
        this.TFArtistaConsultar.setText(artista);
        this.CBGeneroConsultar.setSelectedItem(genero);
    }//GEN-LAST:event_TConsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBGeneroConsultar;
    private javax.swing.JComboBox<String> CBGeneroRegistrar;
    private javax.swing.JLabel LabelArtistaConsultar;
    private javax.swing.JLabel LabelArtistaRegistrar;
    private javax.swing.JLabel LabelGeneroConsultar;
    private javax.swing.JLabel LabelGeneroRegistrar;
    private javax.swing.JLabel LabelIDConsultar;
    private javax.swing.JLabel LabelNombreConsultar;
    private javax.swing.JLabel LabelNombreRegistrar;
    private javax.swing.JLabel LabelRespuestaConsultar;
    private javax.swing.JLabel LabelRespuestaRegistrar;
    private javax.swing.JLabel LabelTituloRegistrar;
    private javax.swing.JPanel PanelConsultar;
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JTable TConsultar;
    private javax.swing.JTextField TFArtistaConsultar;
    private javax.swing.JTextField TFArtistaRegistrar;
    private javax.swing.JTextField TFIDConsultar;
    private javax.swing.JTextField TFNombreConsultar;
    private javax.swing.JTextField TFNombreRegistrar;
    private javax.swing.JTabbedPane TabbedPaneMusica;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
